---
#
# File: docker-compose.yml
#
# Assembles Docker images to run the ocr4all backend containers.
#
# Author: Herbert Baier (herbert.baier@uni-wuerzburg.de)
# Date: 16.04.2024
#
version: "3.9"

services:
  msa-ocrd:
    hostname: msa-ocrd
    build:
      context: ocr4all-app-ocrd-msa
      dockerfile: Dockerfile
      args:
        - TAG=${OCRD_TAG:-2024-04-29}
        - JAVA_VERSION=${OCRD_JAVA_VERSION:-17}
        - APP_VERSION=${OCRD_APP_VERSION:-1.0-SNAPSHOT}
    user: "${UID:-}"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${OCRD_PROFILES:-logging-debug,ocrd-logging-discard,msa-api,docker}
    volumes:
      - ${WORKSPACE_PROJECT:-~/ocr4all/docker/workspace/projects}:/srv/ocr4all/projects
      - ${WORKSPACE_RESOURCES_ORCD:-~/ocr4all/docker/opt/ocr-d/resources}:/usr/local/share/ocrd-resources
    ports:
      - "${OCRD_API_PORT:-127.0.0.1:9091}:8080"
  server:
    build:
      context: ocr4all-app
      dockerfile: Dockerfile
      args:
        - TAG=${OCR4ALL_TAG:-17-jdk-slim}
        - APP_VERSION=${OCR4ALL_APP_VERSION:-1.0-SNAPSHOT}
    user: "${UID:-}"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${OCR4ALL_PROFILES:-logging-debug,server,api,documentation,docker}
    volumes:
      - ${WORKSPACE:-~/ocr4all/docker}:/srv/ocr4all
    ports:
      - "${OCR4ALL_API_PORT:-9090}:8080"
    depends_on:
      - msa-ocrd
